Gym/Gym/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("gym_registro.urls")),
    path('accounts/', include('django.contrib.auth.urls')),  # Utiliza las vistas de autenticación predeterminadas de Django
    path('accounts/login/', auth_views.LoginView.as_view(), name='login'),  # Ruta para iniciar sesión
    path('accounts/logout/', auth_views.LogoutView.as_view(), name='logout'),
      
      

  # Ruta para cerrar sesión
]

Gym/gym_registro/models.py
from django.db import models

class Admin(models.Model):
    identificacion_propietario = models.CharField(max_length=20, blank=True, null=True)
    documento = models.CharField(max_length=20, unique=True, blank=True, null=True)
    nombre_admin = models.CharField(max_length=50, blank=False, null=False)
    apellido_admin = models.CharField(max_length=50, blank=False, null=False)
    contrasena_admin = models.CharField(max_length=128, blank=False, null=False)
    correo = models.EmailField(max_length=100, blank=False, null=False)

class Coach(models.Model):
    documento = models.CharField(max_length=20, unique=True, blank=True, null=True)
    nombre = models.CharField(max_length=50, blank=False, null=False)
    apellido = models.CharField(max_length=50, blank=False, null=False)
    edad = models.IntegerField(blank=False, null=False)
    telefono = models.CharField(max_length=15, blank=True, null=True)
    correo = models.EmailField(max_length=100, blank=False, null=False)
    experiencia = models.IntegerField(blank=True, null=True)
    contrasena = models.CharField(max_length=128, blank=False, null=False)
    ficha_de_ingreso = models.CharField(max_length=10, blank=False, null=False)
    genero = models.CharField(max_length=10, blank=False, null=False)
    
    TURNO_CHOICES=(
        (1, '-----'),
        (2, 'Noche'),
        (3, 'Dia'),
    )
    
    ESPECIALIZACIONES_CHOICES = (
        (1, '-------'),
        (2, 'Fitness'),
        (3, 'Pilates'),
        (4, 'Rehabilitacion fisica'),
        (5, 'Plan para mayores'),
        (6, 'Yoga'),
        (7, 'Gimnasia')
        # Agrega más especializaciones según sea necesario
    )
    turno = models.IntegerField(choices=TURNO_CHOICES, blank=True, null=True)
    typo_id = models.IntegerField(choices=ESPECIALIZACIONES_CHOICES, blank=True, null=True)
    usuarios = models.ManyToManyField('User', related_name='coaches', blank=True)  # Agrega blank=True
    admin = models.ForeignKey(Admin, on_delete=models.CASCADE, related_name='coaches', blank=True, null=True)
    GENE_CHOICES=(
        (1, '---------'),
        (2, 'Masculino'),
        (3, 'Femenino'),
        (4, 'Otro'),
    )
    genero = models.IntegerField(choices=GENE_CHOICES, blank=True, null=True)

class User(models.Model):
    documento = models.CharField(max_length=20, unique=True, blank=True, null=True)
    nombre = models.CharField(max_length=50, blank=False, null=False)
    apellido = models.CharField(max_length=50, blank=False, null=False)
    genero = models.CharField(max_length=10, blank=False, null=False)
    edad = models.IntegerField(blank=False, null=False)
    telefono = models.CharField(max_length=15, blank=False, null=False)
    contrasena = models.CharField(max_length=128, blank=False, null=False)
    correo = models.EmailField(max_length=100, blank=False, null=False)   
    GENE_CHOICES=(
        (1, 'Masculino'),
        (2, 'Femenino'),
    )
    genero = models.IntegerField(choices=GENE_CHOICES, blank=True, null=True)

class SolicitudesCliente(models.Model):
    peso = models.CharField(max_length=5, blank=True)
    estatura = models.CharField(max_length=4, blank=True)
    objetivos = models.TextField(blank=True)
    correo = models.EmailField(max_length=100, blank=False, null=False)
    admin = models.ForeignKey(Admin, on_delete=models.CASCADE, related_name='solicitudes_clientes', blank=True, null=True)

Gym/templates/signups/signup_administrador.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Registrar Administrador</title>
  <link rel="stylesheet" href="{% static 'signup_admin.css' %}">
  <link rel="preconnect" href="https://fonts.googleapis.com">
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
  <link href="https://fonts.googleapis.com/css2?family=Noto+Sans:ital,wght@0,100..900;1,100..900&display=swap" rel="stylesheet">
</head>
<body>
  <main class="container">
    <form id="formulario_admin" action="{% url 'signup_ad' %}" method="post">
      {% csrf_token %}
      <div class="p_bloque">
        <h3 class="title">Signup Administrador</h3>

        <div class="bloquesito">
          <div class="block">
            {{ admin_form.identificacion_propietario.label_tag }}
            {{ admin_form.identificacion_propietario }}

            {{ admin_form.documento.label_tag }}
            {{ admin_form.documento }}
   
            {{ admin_form.nombre_admin.label_tag }}
            {{ admin_form.nombre_admin }}
          </div>
          
          <div class="block">
            {{ admin_form.apellido_admin.label_tag }}
            {{ admin_form.apellido_admin }}
            {{ admin_form.telefono.label_tag }}
            {{ admin_form.telefono }}
       
            {{ admin_form.correo.label_tag }}
            {{ admin_form.correo }}
  
            {{ admin_form.direccion.label_tag }}
            {{ admin_form.direccion }}
 
            {{ admin_form.contrasena_admin.label_tag }}
            {{ admin_form.contrasena_admin }}
          </div>
        </div>
        <button type="submit" class="button">Registrarse</button>
      </div>
    </form>
  </main>

<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
<script>
$(document).ready(function() {
  $('#formulario_admin').submit(function(e) {
    // Evitar que el formulario se envíe por defecto
    e.preventDefault();

    // Validación de campos aquí
    var nombreAdmin = $('#id_nombre_admin').val();
    if (nombreAdmin.trim() == '') {
      $('#nombre_admin_error').text('Por favor ingresa un nombre.');
      return false; // Detener el envío del formulario si hay un error
    } else {
      $('#nombre_admin_error').text('');
    }

    // Agrega validación para los otros campos

    // Si todos los campos son válidos, envía el formulario
    this.submit();
  });
});
</script>

</body>
</html>

Gym/templates/signups/signup_cliente.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Registrar cliente</title>
  <link rel="stylesheet" href="{% static 'signup_cliente.css' %}">
  <link rel="preconnect" href="https://fonts.googleapis.com">
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
  <link href="https://fonts.googleapis.com/css2?family=Noto+Sans:ital,wght@0,100..900;1,100..900&display=swap"
    rel="stylesheet">
</head>

<body>
  <main class="container">
    <form id="formulario_user" action="{% url 'signup_cl' %}" method="post">
      <div class="p_bloque">
        <h3 class="title">signup de usuario</h3>
        <div class="bloquesito">
          {% csrf_token %}

          <div class="block">
            <div>
              {{ user_form.nombre.label_tag }}
              {{ user_form.nombre }}
              {{ user_form.apellido.label_tag }}
              {{ user_form.apellido }}
              {{ user_form.edad.label_tag }}
              {{ user_form.edad }}
              {{ user_form.genero.label_tag }}
              {{ user_form.genero }}

              
            </div>
          </div>
          <div class="block">
            <div>
              
              {{ user_form.contrasena.label_tag }}
              {{ user_form.contrasena }}

              {{ user_form.correo.label_tag }}
              {{ user_form.correo }}

              {{ user_form.documento.label_tag }}
              {{ user_form.documento }}
              {{ user_form.telefono.label_tag }}
              {{ user_form.telefono }}
          </div>
        </div>

        
      </div><button type="submit" class="button">Registrarse</button>
    </form>
  </main>
  <script>
$(document).ready(function() {
  $('#formulario_user').submit(function(e) {
    // Evitar que el formulario se envíe por defecto
    e.preventDefault();

    // Validación de campos aquí
    var nombreAdmin = $('#id_nombre_user').val();
    if (nombreAdmin.trim() == '') {
      $('#nombre_user_error').text('Por favor ingresa un nombre.');
      return false; // Detener el envío del formulario si hay un error
    } else {
      $('#nombre_user_error').text('');
    }

    // Agrega validación para los otros campos

    // Si todos los campos son válidos, envía el formulario
    this.submit();
  });
});
</script>
</body>

</html>

Gym/templates/signups/signup_entrenador.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Registrar entrenador</title>
  <link rel="stylesheet" href="{% static 'signup_entrenador.css' %}">
  <link rel="preconnect" href="https://fonts.googleapis.com">
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
  <link href="https://fonts.googleapis.com/css2?family=Noto+Sans:ital,wght@0,100..900;1,100..900&display=swap"
    rel="stylesheet">
</head>

<body>
  <main class="container">
    <form action="{% url 'signup_en' %}" method="post" id="formulario_coach">
        {% csrf_token %}
        <div class="p_bloque">
            <h3 class="title">Registro</h3>
            <div class="bloquesito">
                <div class="block">
                    <div>
                        {{ coach_form.documento.label_tag }}
                        {{ coach_form.documento }}
                        {{ coach_form.nombre.label_tag }}
                        {{ coach_form.nombre }}
                        {{ coach_form.apellido.label_tag }}
                        {{ coach_form.apellido }}
                        {{ coach_form.edad.label_tag }}
                        {{ coach_form.edad }}
                    </div>
                </div>
                <div class="block">
                    <div>             
                        {{ coach_form.telefono.label_tag }}
                        {{ coach_form.telefono }}
                        {{ coach_form.correo.label_tag }}
                        {{ coach_form.correo }}
                        {{ coach_form.genero.label_tag }}
                        {{ coach_form.genero }}
                        {{ coach_form.contrasena.label_tag }}
                        {{ coach_form.contrasena }}
                    </div>
                </div>
                <div class="block">
                    <div>
                      {{ coach_form.ficha_de_ingreso.label_tag }}
                        {{ coach_form.ficha_de_ingreso }}
                        {{ coach_form.experiencia.label_tag }}
                        {{ coach_form.experiencia }}
                        {{ coach_form.turno.label_tag }}
                        {{ coach_form.turno }}
                     {{ coach_form.typo_id.label_tag }}
                      {{ coach_form.typo_id }}
                    </div>
                </div>
            </div>
            
            <button type="submit" class="button">Registrarse</button>
        </div>
    </form>
  </main>

  <script>
$(document).ready(function() {
  $('#formulario_coach').submit(function(e) {
    // Evitar que el formulario se envíe por defecto
    e.preventDefault();

    // Validación de campos aquí
    var nombreAdmin = $('#id_nombre_coach').val();
    if (nombreAdmin.trim() == '') {
      $('#nombre_coach_error').text('Por favor ingresa un nombre.');
      return false; // Detener el envío del formulario si hay un error
    } else {
      $('#nombre_coach_error').text('');
    }

    // Agrega validación para los otros campos

    // Si todos los campos son válidos, envía el formulario
    this.submit();
  });
});
</script>
</body>

</html>