Gym/Gym/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("gym_registro.urls")),
    path('accounts/', include('django.contrib.auth.urls')),  # Utiliza las vistas de autenticación predeterminadas de Django
    path('accounts/login/', auth_views.LoginView.as_view(), name='login'),  # Ruta para iniciar sesión
    path('accounts/logout/', auth_views.LogoutView.as_view(), name='logout'),
      
      

  # Ruta para cerrar sesión
]

Gym/gym_registro/models.py
from django.db import models

class Admin(models.Model):
    identificacion_propietario = models.CharField(max_length=20, blank=True, null=True)
    documento = models.CharField(max_length=20, unique=True, blank=True, null=True)
    nombre_admin = models.CharField(max_length=50, blank=False, null=False)
    apellido_admin = models.CharField(max_length=50, blank=False, null=False)
    contrasena_admin = models.CharField(max_length=128, blank=False, null=False)
    correo = models.EmailField(max_length=100, blank=False, null=False)

class Coach(models.Model):
    documento = models.CharField(max_length=20, unique=True, blank=True, null=True)
    nombre = models.CharField(max_length=50, blank=False, null=False)
    apellido = models.CharField(max_length=50, blank=False, null=False)
    edad = models.IntegerField(blank=False, null=False)
    telefono = models.CharField(max_length=15, blank=True, null=True)
    correo = models.EmailField(max_length=100, blank=False, null=False)
    experiencia = models.IntegerField(blank=True, null=True)
    contrasena = models.CharField(max_length=128, blank=False, null=False)
    ficha_de_ingreso = models.CharField(max_length=10, blank=False, null=False)
    genero = models.CharField(max_length=10, blank=False, null=False)
    
    TURNO_CHOICES=(
        (1, '-----'),
        (2, 'Noche'),
        (3, 'Dia'),
    )
    
    ESPECIALIZACIONES_CHOICES = (
        (1, '-------'),
        (2, 'Fitness'),
        (3, 'Pilates'),
        (4, 'Rehabilitacion fisica'),
        (5, 'Plan para mayores'),
        (6, 'Yoga'),
        (7, 'Gimnasia')
        # Agrega más especializaciones según sea necesario
    )
    turno = models.IntegerField(choices=TURNO_CHOICES, blank=True, null=True)
    typo_id = models.IntegerField(choices=ESPECIALIZACIONES_CHOICES, blank=True, null=True)
    usuarios = models.ManyToManyField('User', related_name='coaches', blank=True)  # Agrega blank=True
    admin = models.ForeignKey(Admin, on_delete=models.CASCADE, related_name='coaches', blank=True, null=True)
    GENE_CHOICES=(
        (1, '---------'),
        (2, 'Masculino'),
        (3, 'Femenino'),
        (4, 'Otro'),
    )
    genero = models.IntegerField(choices=GENE_CHOICES, blank=True, null=True)

class User(models.Model):
    documento = models.CharField(max_length=20, unique=True, blank=True, null=True)
    nombre = models.CharField(max_length=50, blank=False, null=False)
    apellido = models.CharField(max_length=50, blank=False, null=False)
    genero = models.CharField(max_length=10, blank=False, null=False)
    edad = models.IntegerField(blank=False, null=False)
    telefono = models.CharField(max_length=15, blank=False, null=False)
    contrasena = models.CharField(max_length=128, blank=False, null=False)
    correo = models.EmailField(max_length=100, blank=False, null=False)   
    GENE_CHOICES=(
        (1, 'Masculino'),
        (2, 'Femenino'),
    )
    genero = models.IntegerField(choices=GENE_CHOICES, blank=True, null=True)

class SolicitudesCliente(models.Model):
    peso = models.CharField(max_length=5, blank=True)
    estatura = models.CharField(max_length=4, blank=True)
    objetivos = models.TextField(blank=True)
    correo = models.EmailField(max_length=100, blank=False, null=False)
    admin = models.ForeignKey(Admin, on_delete=models.CASCADE, related_name='solicitudes_clientes', blank=True, null=True)

Gym/templates/views_especializaion/especializacion_detalle.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Detalle de Especialización y Formulario de Inscripción</title>
</head>
<body>
    <h1>Detalle de Especialización</h1>
    <h2>Información del Coach</h2>
    <p>Ficha de Ingreso: {{ coach.ficha_de_ingreso }}</p>
    <p>Documento: {{ coach.documento }}</p>
    <p>Nombre: {{ coach.nombre }}</p>
    <p>Apellido: {{ coach.apellido }}</p>
    <p>Edad: {{ coach.edad }}</p>
    <p>Género: {{ coach.genero }}</p>
    <p>Teléfono: {{ coach.telefono }}</p>
    <p>Correo: {{ coach.correo }}</p>
    <p>Dirección: {{ coach.direccion }}</p>
    <p>Experiencia: {{ coach.experiencia }}</p>
    <p>Especialización: {{ coach.especializacion }}</p>
    <p>Horarios: {{ coach.horarios }}</p>
<a href="{% url 'inscripcion' %}">inscripcion</a>

Gym/templates/views_especializaion/especializaciones.html
<!-- especializaciones.html -->
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Especializaciones</title>
</head>
<body>
    <h1>Especializaciones</h1>
    <ul>
        {% for especializacion in especializaciones %}
        <li><a href="{% url 'especializacion_detalle' coach_id=especializacion.id %}">{{ especializacion.nombre }} - {{ especializacion.get_typo_id_display }}</a></li>
        {% endfor %}
    </ul>
</body>
</html>

Gym/templates/views_especializaion/inscripciones.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Perfil del Coach</title>
  <link rel="stylesheet" href="{% static 'main.css' %}">
</head>
<body>
  <div class="card_cn">
    <div class="card_one">
      {% if messages %}
        <ul class="messages">
          {% for message in messages %}
            <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
          {% endfor %}
        </ul>
      {% endif %}
      
      <h2>Ingrese el documento</h2>
      <form action="{% url 'buscar_user_view' %}" method="post">
        {% csrf_token %}
        <label for="documento">Documento:</label>
        <input type="text" id="documento" name="documento" required>
        <button class="button" type="submit">Buscar Usuario</button>
      </form>
      
      {% if show_inscripcion_form %}

        <h1>Formulario de Solicitud de Cliente</h1>
        <form action="{% url 'inscribir_user' %}" method="post">
          {% csrf_token %}

          {{ form_inscripcion.objetivos.label_tag }}
          {{ form_inscripcion.objetivos }}
          {{ form_inscripcion.estatura.label_tag }}
          {{ form_inscripcion.estatura }}
          {{ form_inscripcion.peso.label_tag }}
          {{ form_inscripcion.peso }} 
          {{ form_inscripcion.correo.label_tag }}
          {{ form_inscripcion.correo }} 
          
          <button type="submit">Enviar</button>
        </form>
      {% endif %}
    </div>
  </div>
</body>
</html>